name: daily-cron
on:
  schedule:
    - cron: "0-59 0-23 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl -X GET https://veggies-fruits-jcp2duxjb-wiwo.vercel.app/api/databasecheck
